server:
  port: 9002

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    #org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks